# match the lint rules from flutter_map
include: ./../analysis_options.yaml

# only specify things that should be different from the package
linter:
  rules:
    # using the default parameter values are used as explanation and for showcase
    avoid_redundant_argument_values: false
    # don't enforce documentation for the example app
    public_member_api_docs: false
